traffic

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,12 +1,16 @@
 #!/usr/bin/env bash
-# Redirection:
+set -e  # Exit if any command fails
 
-# Install nginx web server:
-sudo apt -y update
-sudo apt -y upgrade
-sudo apt -y install nginx
-sudo chown -R ubuntu /var/www/
-touch /var/www/html/index.html
-echo "Hello World!" > /var/www/html/index.html
-sudo sed -i "/^}$/i \ \n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\t# Am omar but you can call me dehao\n\t}\n" /etc/nginx/sites-available/default
+# Install Nginx
+sudo apt update -y
+sudo apt install -y nginx
+
+# Start Nginx
 sudo service nginx start
+
+# Add the redirection rule for /redirect_me to the Nginx config
+sed -i "/^}$/i \    location /redirect_me {\n        return 301 https://www.example.com;\n    }" /etc/nginx/sites-available/default
+
+# Test and restart Nginx
+sudo service nginx restart
+
